[package]
name = "clippard"
version = "0.1.1"
edition = "2021"
authors = ["James Koonts <james@koonts.net>"]
description = "clippard"

[dependencies]

enigo = "0.0.14"
magic-crypt = "3.1.12"
keybind = "0.1.0"
x11-clipboard = "0.9.1"
