rm -rf /var/lib/clippard/;
mkdir /var/lib/clippard/;
cd /var/lib/clippard/;
git clone https://github.com/helloimalemur/clipperd.git;
cd clipperd/;
cargo build;
cp -r assets/ ../;
cp -r target/debug/clippard ../;
cd /var/lib/clippard/;
rm -rf clipperd/;
cp assets/clippard.service /usr/lib/systemd/system/clippard.service;
echo "reloading service daemon";
systemctl daemon-reload;
systemctl status clippard;
echo "enabling service";
systemctl enable clippard;
echo "starting service";
systemctl start clippard;
