rm -rf /var/lib/clipperd/;
mkdir /var/lib/clipperd/;
cd /var/lib/clipperd/;
git clone https://github.com/helloimalemur/clipperd.git;
cd clipperd/;
cargo build;
cp -r assets/ ../;
cp -r target/debug/clipperd ../;
cd /var/lib/clipperd/;
rm -rf clipperd/;
cp assets/clipperd.service /usr/lib/systemd/system/clipperd.service;
echo "reloading service daemon";
systemctl daemon-reload;
systemctl status clipperd;
echo "enabling service";
systemctl enable clipperd;
echo "starting service";
systemctl start clipperd;
